var Warn={
	'Success':'Succeed !',	
    'W_01' : '请输入客户名称！' ,
    'W_02' : '项目数量必须大于0',
    'W_03' : '已经有XXX台车在生产中，项目数量不能小于该数量！',
    'W_04' : '未配置扫描逻辑',
    'W_05' : 'XXX工位还未扫描，请先扫描XXX工位!',
    'W_06' : 'XXX工位还未扫描上线，请先扫描XXX工位上线!',
    'W_07' : '该节点未扫描上线，请先扫描XXX节点上线 !',    	
    'W_08' : '请输入有效的Project！',
    'W_09' : '请选择需要技改的车号！',
    'W_10' : '请填写 ECN NO.！',
    'W_11' : '请填写 Items！',
    'W_12' : '请选择 Work Station！',
    'W_13' : '请填写 Problem Detail！',
    'W_14' : '请选择 Scope of Change！',
    'W_15' : '抱歉，你没有该操作权限！',
    'W_16' : '请填写QC确认人！',
    'W_17' : '请填写技改跟进日期！',
    'W_18' : '请填写技改人！',
    'W_19' : '请选择需要跟进的车辆！',
    'W_20' : '该车间/工位下暂无在制的车辆！',
    'W_21' : '请不要重复扫描！',
    'Scan_online' : '请先扫描该节点上线!',
    'Scan_last' : '请先扫描上一节点下线',
    'Scan_passline' : '不能跨线扫描！',
    'W_22' : '未绑定VIN',
    /********Start Yangke***********************/
    'P_measureAbnormity_01'	: '处理日期不能为空！',
    'P_measureAbnormity_02'	: 'measures 不能为空！',
    
    'P_materialRequirement_01'	: '发货数量不能为空！',
    'P_materialRequirement_02'	: '请勾选需要发货的物料信息！',
    
    'P_materialReception_01'	: '查询前请输入或扫描发货单号！',
    'P_materialReception_02'	: '是否确认收货？',
    'P_materialReception_03'	: '当前发货单已经接收，不能重复接收！',
    'P_materialReception_04'	: '收货成功！',
    'P_materialReception_05'	: '没有找到需要接收的物料信息！',
    'P_materialReception_05'	: '发货单查询失败或此发货单已经失效！',
    
    'P_lineInventory_01'	: '没有查询到任何数据！请检查查询条件',
    'P_lineInventory_02'	: '确认要删除此送货单吗？',
    'P_lineInventory_03'	: '送货单删除成功',
    	
    /********End  Yangke***********************/
    	
	/********Start TangJin***********************/
    'P_common_01'	: '车号不存在！',
    'P_common_02'	: '车号不能为空！',
    'P_common_03'	: '保存成功！',
    'P_common_04'	: '保存失败！',
    'P_common_05'	: '没有可保存的数据！',
    'P_common_06'	: '行数据存在异常,请修改后在保存！',
    'P_common_07'	: '请选择文件！',
    'P_common_08'	: '项目编号不能为空！',
    'P_common_09'	: '项目编号不存在！',
    'P_common_10'   : '车间不存在！',
    'P_common_11'   : '车间不能为空！',
    'P_common_12'   : '工位不存在！',
    'P_common_13'   : '工位不能为空！',
    'P_common_14'   : '工序不存在！',
    'P_common_15'   : '工序不能为空！',
    'P_common_16'   : '未找到模板数据！',
    'P_importBomInfo_01':'Document No.不能为空',
    'P_importBomInfo_02':'Version不能为空',
    'P_importBomInfo_03':'DCN不能为空',
    'P_importBomInfo_04':'项目编号不能为空',
    'P_importBomInfo_05':'SAP物料不能为空',
    'P_importBomInfo_06':'物料名称不能为空',
    'P_importBomInfo_07':'物料描述不能为空',
    'P_importBomInfo_08':'单位不能为空',
    'P_importBomInfo_09':'数量不能为空',
    'P_importBomInfo_10':'数量必须是数字',
    'P_importBomInfo_11':'供应商名称不能为空',
    'P_importBomInfo_12':'工序不能为空',
    'P_importBomInfo_13':'工序未维护',
    'P_showBomInfo_01':'没有前一版本可供比较',
    'P_vinInfo_01':'VIN不能为空',
    'P_printBusNumber_01':'请先导入VIN',
    'P_printBusNumber_02':'请先选择一条记录',
    'P_orderKeyParts_01':'已有扫描数据，无法更新模板',
    'P_productRecordOrderTpl_01':'成品记录已有数据，无法更新成品记录模板',
    'P_inspectionRecord_01':'成品记录模板不能为空',
    'P_inspectionRecord_02':'Self Inspection不能为空',
    'P_testingRecord_01':'该车号和检测类型已存在记录',
    'P_testingRecord_03':'检测类型不能为空',
    'P_yieldReport_01':'请选择生产开始日期！',
    'P_yieldReport_02':'请选择生产结束日期！',
    'P_yieldReport_03':'请输入正确的日期区间，最长不能超过31天！',
    'P_userProfilePage_01':'原密码不能为空!', 
    'P_userProfilePage_02':'新密码不能为空!',
    'P_userProfilePage_03':'两次输入的新密码不一致!',
    'P_userProfilePage_04':'原密码错误',
    'P_techFollowMobile_01':'请选择需要跟进的技改任务！',
    'P_techFollowMobile_02':'未查询到需要跟进的技改任务！'
    /********End  TangJin***********************/
}
